apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer-system-config
data:
  APP_ENV: "k8s"
  DATABASE_URL: "postgresql+psycopg://postgres:postgres@postgres:5432/transfer_db"
  REDIS_URL: "redis://redis:6379/0"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672//"
  CACHE_ENABLED: "true"
  LOG_LEVEL: "INFO"
  NOTIFY_FAIL_RATE: "0.0"
  NOTIFY_DELAY_SEC: "2.0"
