apiVersion: v1
kind: Secret
metadata:
  name: transfer-system-secrets
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "transfer_db"
  SENTRY_DSN: ""
